title: Bucket of Code

remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - site.github.json  # a file containing the contents of site.github variable on Github